Истина где-то на сервере
htmlacademy-react/678357-what-to-watch-10 pull request #10
Opened 2022-07-30 17:47 UTC by Gravi7ON

2022-07-31 09:50 UTC, KletskovG requested changes

2022-07-31 09:50 UTC, KletskovG commented on project/src/pages/main/main.tsx
> +            movies.length <= filmsPerStep || (genreTab !== ALL_GENRES && moviesByGenre.length <= filmsPerStep) ?
Вынеси, пожалуйста, эти условия в отдельную переменную, потому что тут все сливается в одно и тяжело понять 

А в этом месте просто оставить такое же написание, только вместо нескольких условий переменная будет

2022-07-31 09:50 UTC, KletskovG commented on project/package.json
> +    "http-status-codes": "^2.2.0",
Не очень понимаю, для чего тут этот пакет, можно спокойно и без него обойтись

2022-07-31 09:50 UTC, KletskovG commented on project/src/services/api.ts
> +  [StatusCodes.BAD_REQUEST]: true,
Тут можно просто оставить числа

2022-07-31 09:50 UTC, KletskovG commented on project/src/services/api.ts
> +  [StatusCodes.BAD_REQUEST]: true,
Или можешь составить свой собственный enum

Тянуть как можно больше зависимостей в проект не стоит

2022-07-31 11:23 UTC, Gravi7ON commented on project/package.json
> +    "http-status-codes": "^2.2.0",
Сенсей да она в сжатом виде 1.1к объемом, показалось читаемость лучше будет

2022-08-01 04:42 UTC, KletskovG commented on project/package.json
> +    "http-status-codes": "^2.2.0",
Можно такую же читаемость сделать самостоятельность, 1.1кб - это много, тем более, для обычного `enum`

2022-08-01 04:45 UTC, KletskovG approved these changes

2022-08-01 04:45 UTC, KletskovG commented on project/src/services/api.ts
> +  400: true,
Можно сделать отдельный enum, так же, как и было в другом пакете

```ts
enum HTTPStatusCode = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
}

const StatusCodeMapping: Record<number, boolean> = {
  [HTTPStatusCode.BAD_REQUEST]: true,
  // .....
}
```

2022-08-01 04:46 UTC, merged