Больше подробностей (часть 2)
htmlacademy-react/678357-what-to-watch-10 pull request #7
Opened 2022-07-22 15:35 UTC by Gravi7ON

---
:mortar_board: [Больше подробностей (часть 2)](https://up.htmlacademy.ru/react/10/user/678357/tasks/8)

2022-07-22 17:38 UTC, KletskovG requested changes

2022-07-22 17:38 UTC, KletskovG commented on project/src/components/film-info/film-reviews.tsx
> +              comment={comment.comment}
Все эти строчки можно заменить на 

`{...comment}`

В итоге получится 

```jsx
<FIlmComment
  key={index++}
  {...comment}
/>
```

2022-07-22 17:38 UTC, KletskovG commented on project/src/components/film-info/film-reviews.tsx
> +              comment={comment.comment}
Тут такой же момент

2022-07-22 17:38 UTC, KletskovG commented on project/src/components/films-list/films-list.tsx
> +          name={film.name}
И тут такая же история, по аналогии

2022-07-22 17:38 UTC, KletskovG commented on project/src/components/tabs/tabs.tsx
> +    switch(tab) {
Тут можно сделать еще круче, чтобы на будущее можно было легко добавлять табы

```jsx
const tabs = {
  Overview: <FilmInfo film={currentFilm} />,
  Details: <Details film={currentFilm />,
}

if (tab in tabs) { // Тут еще можно попробовать if (tabs[tab])
  return tabs[tab];
}

return <Review comments={comments} />
```

Такой способ очень удобен, потому что с его помощью можно очень легко добавлять или удалять табы, код сам по себе элегантнее

2022-07-22 17:38 UTC, KletskovG commented on project/src/components/tabs/tabs.tsx
> +        <ul className="film-nav__list">
Под  этот список однозначно стоит завести компонент, назвать его, например, `Tabs` 

Внутри него рисуется `<Tab />` для каждого нужного таба, чтобы тут не получалось такого жесткого дублирования

2022-07-22 17:53 UTC, Gravi7ON commented on project/src/components/film-info/film-reviews.tsx
> +              comment={comment.comment}
Интересный момент, получается что-то наподобие объекта с настройками, компонент сам берет те пропы которые необходимы? в случае с фильмом не повлияет на производительность при разворачивании всей полей, где нужны всего 4?

2022-07-23 07:15 UTC, Gravi7ON commented on project/src/components/tabs/tabs.tsx
> +    switch(tab) {
Согласен, это прикольный вариант, но я немного по-другому сделал, зацени)

2022-07-23 07:19 UTC, Gravi7ON commented on project/src/components/tabs/tabs.tsx
> +        <ul className="film-nav__list">
Сенсей здесь не совсем понял идею, я сделал отдельный компонент таббар и в него коллбэком отправил обработчик с состоянием родительского, нам ведь нужно отрисовывать все тайтлы табов в `<nav>` и отдельно информацию о фильме по одиночке

2022-07-24 07:08 UTC, KletskovG commented on project/src/components/film-info/film-reviews.tsx
> +              comment={comment.comment}
Нет, это никак не влияет на производительность - тут такая же операция, что была до этого, только написана короче

2022-07-24 07:08 UTC, merged

2022-07-24 07:10 UTC, KletskovG commented on project/src/components/tabs/tabs.tsx
> +        <ul className="film-nav__list">
Нужно, чтобы была вот такая структура, можно потом доделать 

```jsx
<Tabbar>
  <Tab title={'First' />
  <Tab title={'Second'} />
</Tabbar>
```